name: Fast Build Sysupgrade

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Install packages
      - name: Install packages
        run: |
          sudo apt update

          sudo apt install -y \
            wget \
            curl \
            tar \
            zstd \
            xz-utils \
            squashfs-tools \
            fakeroot \
            rsync

      # Download latest ImageBuilder
      - name: Download ImageBuilder
        run: |
          wget https://downloads.openwrt.org/releases/25.12.4/targets/ipq806x/generic/openwrt-imagebuilder-25.12.4-ipq806x-generic.Linux-x86_64.tar.zst

          tar --use-compress-program=unzstd -xf \
            openwrt-imagebuilder-25.12.4-ipq806x-generic.Linux-x86_64.tar.zst

          IMAGEBUILDER_DIR=$(find . -maxdepth 1 -type d | grep openwrt-imagebuilder | head -1)

          echo "Found: $IMAGEBUILDER_DIR"

          mv "$IMAGEBUILDER_DIR" imagebuilder

      # Cleanup invalid extracted firmware dirs
      - name: Cleanup rootfs
        run: |
          rm -rf rootfs/dev || true
          rm -rf rootfs/proc || true
          rm -rf rootfs/sys || true
          rm -rf rootfs/tmp || true
          rm -rf rootfs/rom || true
          rm -rf rootfs/overlay || true
          rm -rf rootfs/usr/lib/opkg || true

      # Prepare files
      - name: Prepare custom files
        run: |
          mkdir -p imagebuilder/files

          if [ -d rootfs/etc ]; then
            mkdir -p imagebuilder/files/etc

            rsync -a \
              rootfs/etc/ \
              imagebuilder/files/etc/
          fi

          if [ -d rootfs/www ]; then
            mkdir -p imagebuilder/files/www

            rsync -a \
              rootfs/www/ \
              imagebuilder/files/www/
          fi

          if [ -d rootfs/root ]; then
            mkdir -p imagebuilder/files/root

            rsync -a \
              rootfs/root/ \
              imagebuilder/files/root/
          fi

      # Show custom files
      - name: Show custom files
        run: |
          echo "===== CUSTOM FILES ====="

          find imagebuilder/files | head -300

      # Build firmware
      - name: Build firmware
        run: |
          cd imagebuilder

          make image \
            PROFILE="ruijie_rg-mtfi-m520" \
            PACKAGES="" \
            FILES="files"

      # Show firmware
      - name: Show firmware
        run: |
          find imagebuilder/bin/targets/ -type f

      # Upload firmware
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: sysupgrade
          path: imagebuilder/bin/targets/ipq806x/generic/*sysupgrade.bin
